Repository rsmp-nordic/rsmp_validator, pull requests merged in 2024-08, with the labels that each got.

#403 Add workflow for La Semaforica Cartesio
  .github/workflows/semaforica_cartesio.yaml
  config/semaforica_cartesio.yaml
Labels: testhub

#405 use .yaml for workflows
  .github/workflows/build_docs.yaml
  .github/workflows/docker.yaml
  .github/workflows/gem_supervisor.yaml
  .github/workflows/gem_tlc.yaml
  .github/workflows/swarco_itc3.yaml
Labels: testhub

#408 M0022 cancellation
  Gemfile.lock
  config/gem_tlc.yaml
  spec/site/tlc/alarm_spec.rb
  spec/site/tlc/clock_spec.rb
  spec/site/tlc/signal_priority_spec.rb
  spec/spec_helper.rb
  spec/support/command_helpers.rb
  spec/support/formatters/steps.rb
  spec/support/signal_group_sequence_helper.rb
  spec/support/signal_priority_request_helper.rb
Labels: enhancement, testhub

#410 update action versions in docker workflow
  .github/workflows/docker.yaml
Labels: tooling

#418 Update semaforica_cartesio.yaml with Core version 3.2.2, SXL version …
  config/semaforica_cartesio.yaml
Labels: testhub
